import { useEffect, useMemo, useRef, useState, type CSSProperties } from 'react'
import { BsChevronDown, BsChevronUp, BsDownload, BsEye, BsFunnel, BsSend } from 'react-icons/bs'
import { apiFetch } from '../../../api/client'
import TaskDetailsModal from '../../../shared/components/TaskDetailsModal'
import { useAlert } from '../../../shared/alerts/useAlert'
import { checkExpertActiveTask, endExpertTask, startExpertTask, type EndTaskStatus, type ExpertTaskItem } from '../api/expertTasksApi'
import './ExpertGroupedTaskBoard.css'

type Task = ExpertTaskItem & { displayStatus: string }
type Props = { tasks: ExpertTaskItem[]; loading: boolean; error: string | null; currentUserId: number; onTaskUpdated: () => Promise<void>; sendingReport: boolean; onSendReport: () => Promise<void> }
type GroupKey = 'today' | 'week' | 'month' | 'previous'

const statusLabel = (value: string) => {
  const status = value.trim().toLowerCase()
  if (status.includes('progress')) return 'In Progress'
  if (status.includes('complete')) return 'Completed'
  if (status.includes('cancel')) return 'Cancelled'
  if (status.includes('reschedule')) return 'Rescheduled'
  if (status.includes('show')) return 'No Show'
  if (status.includes('assign')) return 'Assigned'
  if (status.includes('pending')) return 'Pending'
  return value || 'Unknown'
}
const dateParts = (value: string) => { const [y, m, d] = value.split('-').map(Number); return y && m && d ? { y, m, d } : null }
const dateKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const formatDate = (value: string) => { const p = dateParts(value); return p ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(p.y, p.m - 1, p.d)) : '—' }
const toUtcFromIst = (date: string, time: string) => { const p = dateParts(date); const [h, m, s = 0] = time.split(':').map(Number); return p && !Number.isNaN(h) ? new Date(Date.UTC(p.y, p.m - 1, p.d, h, m, s) - 330 * 60000) : null }
const formatTime = (task: Task, zone: string) => { const start = toUtcFromIst(task.due_date, task.start_time); const end = toUtcFromIst(task.due_date, task.end_time); if (!start || !end) return '—'; const f = new Intl.DateTimeFormat('en-US', { hour: '2-digit', minute: '2-digit', hour12: true, timeZone: zone }); return `${f.format(start)} – ${f.format(end)}` }
const getResumeUrl = (task: Task) => String(task.resume_url || task.candidate_resume || '').trim()

export default function ExpertGroupedTaskBoard({ tasks, loading, error, currentUserId, onTaskUpdated, sendingReport, onSendReport }: Props) {
  const { showToast } = useAlert()
  const filterRef = useRef<HTMLDivElement>(null)
  const [search, setSearch] = useState('')
  const [filterOpen, setFilterOpen] = useState(false)
  const [draft, setDraft] = useState({ status: [] as string[], type: [] as string[], assignedBy: [] as string[] })
  const [filters, setFilters] = useState(draft)
  const [open, setOpen] = useState<Record<GroupKey, boolean>>({ today: true, week: true, month: true, previous: true })
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10)
  const [viewTaskId, setViewTaskId] = useState<number | null>(null); const [startTaskId, setStartTaskId] = useState<number | null>(null); const [endTaskId, setEndTaskId] = useState<number | null>(null)
  const [endStatus, setEndStatus] = useState<EndTaskStatus | ''>(''); const [endComment, setEndComment] = useState(''); const [actionLoading, setActionLoading] = useState(false); const [actionError, setActionError] = useState<string | null>(null)
  const [activeTaskId, setActiveTaskId] = useState<number | null>(null)
  const mapped = useMemo(() => tasks.map(task => ({ ...task, displayStatus: statusLabel(task.status_name) })), [tasks])
  const options = useMemo(() => ({ status: [...new Set(mapped.map(t => t.displayStatus))].sort(), type: [...new Set(mapped.map(t => t.task_type || t.support_type || t.title).filter(Boolean))].sort(), assignedBy: [...new Set(mapped.map(t => t.assigned_by_name).filter(Boolean))].sort() }), [mapped])
  useEffect(() => { void checkExpertActiveTask().then(x => setActiveTaskId(x.activeTaskId)).catch(() => setActiveTaskId(null)) }, [tasks])
  useEffect(() => { const close = (e: MouseEvent) => { if (!filterRef.current?.contains(e.target as Node)) setFilterOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [])
  const filtered = useMemo(() => mapped.filter(task => {
    const haystack = `${task.task_id} ${task.title} ${task.task_type} ${task.support_type} ${task.candidate_name} ${task.company_name} ${task.assigned_to_name} ${task.assigned_by_name}`.toLowerCase()
    return haystack.includes(search.trim().toLowerCase()) && (!filters.status.length || filters.status.includes(task.displayStatus)) && (!filters.type.length || filters.type.includes(task.task_type || task.support_type || task.title)) && (!filters.assignedBy.length || filters.assignedBy.includes(task.assigned_by_name))
  }), [mapped, search, filters])
  const groups = useMemo(() => {
    const now = new Date(), today = dateKey(now), day = now.getDay(), mondayOffset = day === 0 ? -6 : 1 - day
    const weekStart = new Date(now.getFullYear(), now.getMonth(), now.getDate() + mondayOffset), weekEnd = new Date(weekStart.getFullYear(), weekStart.getMonth(), weekStart.getDate() + 6)
    const result: Record<GroupKey, Task[]> = { today: [], week: [], month: [], previous: [] }
    filtered.forEach(task => { const p = dateParts(task.due_date); if (!p) return result.previous.push(task); const local = new Date(p.y, p.m - 1, p.d); if (task.due_date === today) result.today.push(task); else if (local >= weekStart && local <= weekEnd) result.week.push(task); else if (p.y === now.getFullYear() && p.m === now.getMonth() + 1) result.month.push(task); else result.previous.push(task) })
    Object.values(result).forEach(list => list.sort((a, b) => b.due_date.localeCompare(a.due_date) || b.task_id - a.task_id)); return result
  }, [filtered])
  useEffect(() => setPage(1), [search, filters])
  const totalPages = Math.max(1, Math.ceil(groups.previous.length / pageSize)), safePage = Math.min(page, totalPages), previousRows = groups.previous.slice((safePage - 1) * pageSize, safePage * pageSize)
  const activeCount = filters.status.length + filters.type.length + filters.assignedBy.length
  const toggleDraft = (key: keyof typeof draft, value: string) => setDraft(current => ({ ...current, [key]: current[key].includes(value) ? current[key].filter(x => x !== value) : [...current[key], value] }))
  const isMine = (task: Task) => task.is_own_task === 1 || task.assigned_to_id === currentUserId
  const canStart = (task: Task) => isMine(task) && ['Pending', 'Assigned'].includes(task.displayStatus) && (!activeTaskId || activeTaskId === task.task_id)
  const selectedTask = mapped.find(task => task.task_id === viewTaskId) ?? null
  const downloadFile = async (ref: string) => { const name = ref.split('/').pop(); if (!name) return; const response = await apiFetch(`/tasks/file?file=${encodeURIComponent(name)}`); if (!response.ok) return; const url = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url) }
  const renderActions = (task: Task) => <div className="expert-board__actions"><button title="View Task" onClick={() => setViewTaskId(task.task_id)}><BsEye /></button>{getResumeUrl(task) && <button title="Download Resume" onClick={() => window.open(getResumeUrl(task), '_blank', 'noopener,noreferrer')}><BsDownload /></button>}{task.file_url && <button title="Download" onClick={() => void downloadFile(task.file_url)}><BsDownload /></button>}{['Pending', 'Assigned'].includes(task.displayStatus) && <button className="expert-board__text-action" disabled={!canStart(task)} title={canStart(task) ? 'Start Task' : 'Another task is already in progress'} onClick={() => setStartTaskId(task.task_id)}>Start</button>}{isMine(task) && task.displayStatus === 'In Progress' && <button className="expert-board__text-action" title="End Task" onClick={() => { setEndTaskId(task.task_id); setEndStatus(''); setEndComment('') }}>End</button>}</div>
  const renderTable = (rows: Task[], empty: string) => <div className="expert-board__table-wrap"><table><thead><tr><th className="sticky">Actions</th><th>Status</th><th>Date (IST)</th><th>Time (IST)</th><th>Time (ET)</th><th>Candidate Name</th><th>Task Type / Title</th><th>Assigned To</th><th>Assigned By</th></tr></thead><tbody>{loading && <tr><td colSpan={9}>Loading tasks…</td></tr>}{!loading && error && <tr><td className="error" colSpan={9}>{error}</td></tr>}{!loading && !error && !rows.length && <tr><td className="empty" colSpan={9}>{activeCount || search ? 'No matching tasks.' : empty}</td></tr>}{!loading && !error && rows.map(task => <tr key={task.task_id}><td className="sticky">{renderActions(task)}</td><td><span className={`expert-board__status status-${task.displayStatus.toLowerCase().replaceAll(' ', '-')}`}>{task.displayStatus}</span></td><td>{formatDate(task.due_date)}</td><td>{formatTime(task, 'Asia/Kolkata')}</td><td>{formatTime(task, 'America/New_York')}</td><td title={task.candidate_name}>{task.candidate_name || '—'}</td><td className="truncate" title={task.title || task.task_type}>{task.title || task.task_type || '—'}</td><td>{task.is_own_task === 1 ? 'Me' : task.assigned_to_name || '—'}</td><td>{task.assigned_by_name || '—'}</td></tr>)}</tbody></table></div>
  const group = (key: GroupKey, title: string, accent: string, rows: Task[], empty: string, count = rows.length) => <section className="expert-board__group" style={{ '--accent': accent } as CSSProperties}><button className="expert-board__group-head" onClick={() => setOpen(x => ({ ...x, [key]: !x[key] }))} aria-expanded={open[key]}>{open[key] ? <BsChevronDown /> : <BsChevronUp />}<strong>{title}</strong><span>{count} {count === 1 ? 'Task' : 'Tasks'}</span><i />{open[key] ? <BsChevronUp /> : <BsChevronDown />}</button>{open[key] && renderTable(rows, empty)}</section>
  return <div className="expert-board">
    <div className="expert-board__toolbar"><label><span>⌕</span><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search task, candidate, ID..." /></label><div ref={filterRef} className="expert-board__filter-anchor"><button className={`expert-board__filter-button${activeCount ? ' active' : ''}`} onClick={() => { setDraft(filters); setFilterOpen(x => !x) }}><BsFunnel /> Filter {activeCount > 0 && <b>{activeCount}</b>} <BsChevronDown /></button>{filterOpen && <div className="expert-board__popover"><header><strong>Quick Filters</strong><small>Filter tasks across all groups</small></header>{([['status','Status'],['type','Task Type'],['assignedBy','Assigned By']] as const).map(([key,label]) => <div className="expert-board__filter-row" key={key}><h4>{label}</h4><div>{options[key].map(value => <button className={draft[key].includes(value) ? 'selected' : ''} key={value} onClick={() => toggleDraft(key, value)}>{value}</button>)}</div></div>)}<footer><button onClick={() => setDraft({ status: [], type: [], assignedBy: [] })}>Clear All</button><button className="button--primary" onClick={() => { setFilters(draft); setFilterOpen(false) }}>Apply Filters</button></footer></div>}</div><button className="button button--primary expert-board__report" disabled={sendingReport} onClick={() => void onSendReport()}><BsSend /> {sendingReport ? 'Sending…' : 'Send Report Now'}</button></div>
    {group('today', "Today's Tasks", '#1464df', groups.today, 'No tasks scheduled today.')}{group('week', 'This Week', '#0891b2', groups.week, 'No additional tasks scheduled this week.')}{group('month', 'This Month', '#7c3aed', groups.month, 'No additional tasks scheduled this month.')}{group('previous', 'Previous Tasks', '#183b6b', previousRows, 'No previous tasks found.', groups.previous.length)}
    {open.previous && groups.previous.length > 0 && <div className="expert-board__pagination"><span>Showing {(safePage - 1) * pageSize + 1} to {Math.min(safePage * pageSize, groups.previous.length)} of {groups.previous.length} tasks</span><label>Rows per page <select value={pageSize} onChange={e => { setPageSize(Number(e.target.value)); setPage(1) }}>{[10,50,100,200,500].map(n => <option key={n}>{n}</option>)}</select></label><nav><button disabled={safePage === 1} onClick={() => setPage(safePage - 1)}>‹</button>{Array.from({ length: totalPages }, (_, i) => i + 1).filter(n => totalPages <= 7 || n === 1 || n === totalPages || Math.abs(n-safePage) <= 1).map((n,i,a) => <span key={n}>{i > 0 && n-a[i-1] > 1 && <em>…</em>}<button className={n === safePage ? 'current' : ''} onClick={() => setPage(n)}>{n}</button></span>)}<button disabled={safePage === totalPages} onClick={() => setPage(safePage + 1)}>›</button></nav></div>}
    <TaskDetailsModal isOpen={!!selectedTask} role="expert" task={selectedTask ? { taskId:selectedTask.task_id,title:selectedTask.title,status:selectedTask.displayStatus,candidateName:selectedTask.candidate_name,supportType:selectedTask.support_type,assignedTo:selectedTask.is_own_task===1?'Me':selectedTask.assigned_to_name,assignedBy:selectedTask.assigned_by_name,dueDate:selectedTask.due_date,startTime:selectedTask.start_time,endTime:selectedTask.end_time,description:selectedTask.description }: null} onClose={() => setViewTaskId(null)} />
    {startTaskId && <div className="modal-overlay" onClick={() => setStartTaskId(null)}><div className="modal-card expert-board__modal" onClick={e => e.stopPropagation()}><h3>Start Task</h3><p>Are you sure you want to start this task?</p>{actionError && <p className="error">{actionError}</p>}<footer><button onClick={() => setStartTaskId(null)}>Cancel</button><button className="button button--primary" disabled={actionLoading} onClick={async () => { try { setActionLoading(true); await startExpertTask(startTaskId); setStartTaskId(null); showToast({type:'success',message:'Task started successfully.'}); await onTaskUpdated() } catch { setActionError('Unable to start task. Please try again.') } finally { setActionLoading(false) } }}>Yes, Start Task</button></footer></div></div>}
    {endTaskId && <div className="modal-overlay" onClick={() => setEndTaskId(null)}><div className="modal-card expert-board__modal" onClick={e => e.stopPropagation()}><h3>End Task</h3><label>Status<select value={endStatus} onChange={e => setEndStatus(e.target.value as EndTaskStatus)}><option value="">Select status</option>{['Completed','Cancelled','No Show','Rescheduled'].map(x => <option key={x}>{x}</option>)}</select></label><label>Comment<textarea value={endComment} onChange={e => setEndComment(e.target.value)} /></label>{actionError && <p className="error">{actionError}</p>}<footer><button onClick={() => setEndTaskId(null)}>Cancel</button><button className="button button--primary" disabled={actionLoading} onClick={async () => { if (!endStatus || !endComment.trim()) return setActionError('Status and comment are required.'); try { setActionLoading(true); await endExpertTask(endTaskId,endStatus,endComment.trim()); setEndTaskId(null); showToast({type:'success',message:'Task updated successfully.'}); await onTaskUpdated() } catch(e) { setActionError(e instanceof Error ? e.message : 'Unable to end task.') } finally { setActionLoading(false) } }}>Submit</button></footer></div></div>}
  </div>
}
